pipelines:
  default:
    - step:
        name: Pre-pull docker images
        size: 2x # More memory
        services:
          - docker
        caches:
          - docker
        script:
          - docker pull ros:humble
    - step:
        name: Build and run tests
        size: 2x # More memory
        services:
          - docker
        caches:
          - docker
        script:
          - export DOCKER_IMAGE="ros:humble"
          # TODO: revert to upstream when merged
          - git clone --quiet --depth 1 https://github.com/AndyZe/industrial_ci .industrial_ci -b no_docker_init
          - .industrial_ci/bitbucket.sh ROS_DISTRO=humble
    - step:
        name: Clang format
        size: 2x # More memory
        services:
          - docker
        caches:
          - docker
        script:
          - export DOCKER_IMAGE="ros:humble"
          - export CLANG_FORMAT_CHECK="file"
          - export CLANG_FORMAT_VERSION="14"
          # Don't run clang-format on these directories
          - rm -rf ./osal ./oshw ./soem
          # TODO: revert to upstream when merged
          - git clone --quiet --depth 1 https://github.com/AndyZe/industrial_ci .industrial_ci -b no_docker_init
          - .industrial_ci/bitbucket.sh ROS_DISTRO=humble
definitions:
  services:
    docker:
      memory: 7100
