name: Docker

on: [push, workflow_dispatch]

jobs:
  docker:
    strategy:
      matrix:
          ROS_DISTRO: [humble, jazzy, rolling]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: ROS_DISTRO=${{matrix.ROS_DISTRO}}
          #platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/synapticon/synapticon_ros2_control:latest