name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: main}
          - {ROS_DISTRO: jazzy, ROS_REPO: main}
          - {ROS_DISTRO: rolling, ROS_REPO: main}
        ubuntu_version:
          - 20.04
          - 22.04
          - latest  # This will still include Ubuntu 24 (latest)
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
